const typePermissions = {
    Permission: {
        createPermission: "createPermission",
        getAllPermissions: "getAllPermissions",
        getAllPermissionsByID: "getAllPermissionsByID",
        updatePermissions: "updatePermissions",
        deletePermissions: "deletePermissions"
    },
    Account: {
        createAccount: "createAccount",    
        getAllAccounts: "getAllAccounts",    
        getAllAccountsById: "getAllAccountsById",    
        getAllMyAccounts: "getAllMyAccounts",    
        updateAccount: "updateAccount",    
        deleteAccount: "deleteAccount",    
        getMyAccountById: "getMyAccountById",    
    },
    ConfigurationA: {   
        getAllconfigurationsAccounts: "getAllconfigurationsAccounts",    
        getMyConfigurationAccount: "getMyConfigurationAccount",    
        getAllById: "getAllById",    
        updateConfiguration: "updateConfiguration",    
        updateConfigurationById: "updateConfigurationById",    
        updateMyConfiguration: "updateMyConfiguration",    
        deleteConfiguration: "deleteConfiguration",    
    },
    Board: {
        createBoard: "createBoard",    
        getAllBoards: "getAllBoards",    
        getAllBoardsById: "getAllBoardsById",    
        getAllMyBoards: "getAllMyBoards",    
        getAllMyBoardsById: "getAllMyBoardsById",    
        updateBoard: "updateBoard",    
        deleteBoard: "deleteBoard", 
        analyticsBoard: 'analyticsBoard',   
        bulkReloadBoard: 'bulkReloadBoard',   
        createFilesBoard: 'createFilesBoard',   
        createFolderBoard: 'createFolderBoard',   
        getFilesBoard: 'getFilesBoard',  
        getAllBoardsByAccount: 'getAllBoardsByAccount',
        getAllMyBoardsSeller: 'getAllMyBoardsSeller',
    },
    Category: {
        createCategory: "createCategory",    
        getAllCategorys: "getAllCategorys",    
        getAllCategorysById: "getAllCategorysById",    
        getAllMyCategorys: "getAllMyCategorys",    
        getAllMyCategorysById: "getAllMyCategorysById",    
        updateCategory: "updateCategory",    
        deleteCategory: "deleteCategory",  
    },
    Leads: {
        createLeads: "createLeads",    
        getAllLeads: "getAllLeads",    
        getAllLeadsById: "getAllLeadsById",    
        getAllMyLeads: "getAllMyLeads",    
        getAllMyLeadsById: "getAllMyLeadsById",    
        updateLeads: "updateLeads",    
        deleteLeads: "deleteLeads",  
    },
    FormLeads: {  
        getAllFormLeads: "getAllFormLeads",    
        getAllMyFormLeads: "getAllMyFormLeads",    
        getAllFormLeadsById: "getAllFormLeadsById",    
        getAllMyFormLeadsById: "getAllMyFormLeadsById",    
        updateLeads: "updateLeads",    
        deleteLeads: "deleteLeads",  
    },
    Logs: {
        createLogs: "createLogs",    
        getAllLogs: "getAllLogs",    
        getAllLogsById: "getAllLogsById",    
        getAllMyLogs: "getAllMyLogs",    
        getAllMyLogsById: "getAllMyLogsById",    
        getAllLogsBySellerBoard: "getAllLogsBySellerBoard",    
    },
    Pauta: {
        createPauta: "createPauta",    
        getAllPauta: "getAllPauta",    
        getAllPautaById: "getAllPautaById",    
        getAllMyPauta: "getAllMyPauta",    
        getAllMyPautaById: "getAllMyPautaById",  
        updatePauta: "updatePauta",    
        deletePauta: "deletePauta",    
        getAllMyPautas: "getAllMyPautas",    
        analityBoard: "analityBoard",    
    },
    User: {
        createUser: "createUser",    
        getAllUsers: "getAllUsers",    
        getMyUser: "getMyUser",    
        getAllUserById: "getAllUserById",    
        bulkReloadUsers: "bulkReloadUsers",  
        updateUser: "updateUser",    
        deleteUser: "deleteUser",    
        getAllMyUsers: "getAllMyUsers",    
        getAllMyUserById: "getAllMyUserById",    
    },
    Campaign: {
        createCampaign: "createCampaign",    
        getAllCampaigns: "getAllCampaigns",    
        getAllMyCampaigns: "getAllMyCampaigns",    
        getAllCampaignsById: "getAllCampaignsById",    
        getAllMyCampaignsById: "getAllMyCampaignsById",    
        getAllCampaignsByBoard: "getAllCampaignsByBoard",    
        getAllMyCampaignsByBoard: "getAllMyCampaignsByBoard",    
        deleteAll: "deleteAll",    
        deleteCampaignById: "deleteCampaignById",    
        deleteMyCampaignById: "deleteMyCampaignById",    
        getMyCampaign: "getMyCampaign",    
        getAllCampaignById: "getAllCampaignById",    
        bulkReloadCampaigns: "bulkReloadCampaigns",  
        updateCampaign: "updateCampaign",    
        deleteCampaign: "deleteCampaign",
    },
    Transsaction: {
        createTranssaction: "createTranssaction",    
        getAllTranssactions: "getAllTranssactions",    
        getAllMyTranssactions: "getAllMyTranssactions",    
        getMyTranssaction: "getMyTranssaction",    
        getAllTranssactionById: "getAllTranssactionById",    
        getAllMyTranssactionById: "getAllMyTranssactionById",    
        validateEpaycoAndCreateUser: "validateEpaycoAndCreateUser",    
        bulkReloadTranssactions: "bulkReloadTranssactions",  
        updateTranssaction: "updateTranssaction",    
        deleteTranssaction: "deleteTranssaction",
    },
    Files: {
        getAllFiles: "getAllFiles",
        getAllMyFiles: "getAllMyFiles",
        getAllFilesById: "getAllFilesById",
        getAllMyFilesById: "getAllMyFilesById",
        deleteAllFiles: "deleteAllFiles",
        deleteFilesById: "deleteFilesById",
    },
    Formats: {
        createFormat: "createFormat",
        getAllFormats: "getAllFormats",
        getAllFormatsById: "getAllFormatsById",
        updateFormat: "updateFormat",
        deleteFormat: "deleteFormat",
    },
    Notifications: {
        getAllNotifications: "getAllNotifications",
        getAllMyNotifications: "getAllMyNotifications",
        updateNotification: "updateNotification",
        getAllNotificationById: "getAllNotificationById",
        getAllMyNotificationById: "getAllMyNotificationById",
        deleteNotificationById: "deleteNotificationById",
    },
    GeneralConfiguration: {
        getAllGConfig: "getAllGConfig",
        updateGConfig: "updateGConfig"
    },
    Landing : {
        getAllLandings: "getAllLandings",
        getAllMyLandings: "getAllMyLandings",
        getAllLandingsById: "getAllLandingsById",
        updateLanding: "updateLanding",
    }
};

module.exports = {typePermissions};